#!/bin/bash
### Use PKG_DIR as working directory.
PKG_DIR=/tmp/_test_spk
rm -rf $PKG_DIR
mkdir -p $PKG_DIR

### get spk packing functions
source /pkgscripts/include/pkg_util.sh

create_package_tgz() {
	local firewere_version=
	local package_tgz_dir=/tmp/_package_tgz
	local binary_dir=$package_tgz_dir/usr/local/bin

	### clear destination directory
	rm -rf $package_tgz_dir && mkdir -p $package_tgz_dir
	cp -av server ui app images $package_tgz_dir
	# make install DESTDIR="$package_tgz_dir" INSTALLDIR="$package_tgz_dir"
	# make packageinstall DESTDIR="$package_tgz_dir" PKG_DIR="$PKG_DIR"
        
	### create package.tgz $1: source_dir $2: dest_dir
	pkg_make_package $package_tgz_dir "${PKG_DIR}"
}

create_spk(){
        cp -av scripts $PKG_DIR/scripts
	cp -av conf $PKG_DIR/conf
	cp INFO $PKG_DIR/INFO
	mkdir -p /image/packages
	pkg_make_spk ${PKG_DIR} "/image/packages" $(pkg_get_spk_family_name)
}

main() {
	create_package_tgz
	create_spk
}

main "$@"
