#!/bin/sh

case $1 in
    start)
        python3 /var/packages/HDF5Viewer/target/server/api.py &
        echo $! > /var/packages/HDF5Viewer/target/server.pid
        ;;
    stop)
        if [ -f /var/packages/HDF5Viewer/target/server.pid ]; then
            kill $(cat /var/packages/HDF5Viewer/target/server.pid)
            rm /var/packages/HDF5Viewer/target/server.pid
        fi
        ;;
    status)
        if [ -f /var/packages/HDF5Viewer/target/server.pid ] && ps -p $(cat /var/packages/HDF5Viewer/target/server.pid) > /dev/null; then
            echo "running"
        else
            echo "stopped"
        fi
        ;;
esac
