// Generated by generate_config_default.py
#ifndef IOWARP_CAE_CONF_CLIENT_DEFAULT_H_
#define IOWARP_CAE_CONF_CLIENT_DEFAULT_H_

#include <string>

namespace cae {

static const char *kCaeClientDefaultConfigStr = R"(
base_adapter_mode: kDefault
file_adapter_configs:
- mode: kDefault
  page_size: 1MB
  path: /*
file_page_size: 1024KB
flushing_mode: kAsync
path_exclusions:
- /*
path_inclusions:
- ''

)";

} // namespace cae

#endif // IOWARP_CAE_CONF_CLIENT_DEFAULT_H_
